spring.application.name=demo

spring.datasource.url=jdbc:postgresql://localhost:5432/vertex_db
spring.datasource.username=postgres
spring.datasource.password= ${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.docker.compose.enabled=false
server.port=8087
frontend.url=http://localhost:3000
#一旦dockerオフにする。中途半端に設定してたから実行引っ掛かる　3/14
#他のプロジェクトのポートと競合したから8087に変更　3/14
